version: '3'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: Ogiroi1@12212
      POSTGRES_DB: prisma_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prisma_user:Ogiroi1%4012212@db:5432/prisma_db

volumes:
  pgdata:
