version: '3'

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://prisma_user:Ogiroi1%4012212@host.docker.internal:5432/prisma_db

volumes:
  pgdata:
