version: '1.0'

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://prisma_user:Ogiroi1@12212@172.17.0.1:5432/prisma_db